### PR TITLE
Lotte and Ulrik's work refering to rev-AD implementation for s

### PR DESCRIPTION
**Pull request by coancea**
…an and histos together with tests

### CODE REVIEW

**Comment by Munksgaard** [comment]
Wtf...

**Comment by athas** [comment]
Fails on the ISPC backend.  My hunch is that we may be generating weird scans of a kind the ISPC backend has never seen before.

**Comment by athas** [comment]
Some of these test programs are way too large and have tons of unused entry points.  I'd really like to clean this up because otherwise it will never happen, and they will slow down the test suite forever.

**Comment by athas** [comment]
Actually it's not so bad.  It's only the two "benchtests" files that are messy.

**Pull request merged**
