### PR TITLE
Add png2data tool

### LINKED ISSUE #794: More data conversion tools
I wrote [data2png.py](https://github.com/diku-dk/futhark/blob/master/tools/data2png.py) for converting Futhark data dumps to PNG files.  It has already proven quite useful.  I have come to to realise that I would also like a `png2data`, and probably converters for all kinds of other file formats.  Audio?  Why not!  Writing these in Python is probably easiest, but I'm not too picky.

### PR DESCRIPTION
**Pull request by Munksgaard**
Fixes #794, at least partly.

### CODE REVIEW

**Comment by athas** [comment]
Can you clarify which PNG formats this will work with?  E.g. what happens if there is or is not an alpha channel?

**Comment by Munksgaard** [comment]
Right now it only handles RGB-type PNGs. Transparency and grayscale cause a crash. I'll see if I can make it a bit more robust.

**Comment by athas** [comment]
It's not necessarily important that it can handle anything but RGB.  Just put a comment indicating its current restrictions .

**Comment by athas** [comment]
Also, you might want to document whether the pixels are ARGB or RGBA or what.  I think it's the former based on a quick inspection.

**Comment by Munksgaard** [comment]
I've tried to clarify what png2data supports.

**Pull request merged**
