### PR TITLE
Merge master into register tiling branch

### PR DESCRIPTION
**Pull request by athas**
This is required before I can implement code generation for register tiling.

### CODE REVIEW

**Comment by sortraev** [comment]
Hey Troels! Sorry, I only just got home to my laptop, but it is done now.
Good evening and good weekend.

**Comment by athas** [comment]
Why did you merge manually instead of merging this pull request?  Now your code does not work.

**Comment by sortraev** [comment]
That's a good question! Unfortunately, I have no good answer other than
that I'm not very good with git.
I thought merging manually would be equivalent. I have undone my screwup,
but I shall patiently
await a new pull request in fear of simply causing more havoc.

**Comment by athas** [comment]
I have reopened the pull request.  Just go to its webpage and press the merge button.

**Pull request merged**
