### PR TITLE
Support multiple entry points when auto tuning

### LINKED ISSUE #830: futhark autotune doesn't allow files without main
It seems like `futhark autotune` doesn't allow working on files that don't have a `main` function:

```futhark
-- ==
-- entry: foo
-- compiled random input { [10]f32 }
-- auto output
entry foo (xs: []f32): []f32 = xs
```

```
$ futhark autotune foo.fut
Compiling foo.fut...
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
user error (Program does not have a 'main' entry point with datasets.)
```

Given that we can run the program just fine (with `--entry-point`) and that both `futhark bench` and `futhark test` work, this seems like a strange restriction.

### PR DESCRIPTION
**Pull request by Munksgaard**
Also supports having no `main` function.

Fixes #830

### CODE REVIEW

**Comment by Munksgaard** [comment]
The implementation currently doesn't try to guess anything about which tuning parameters belong to which function.

Initially I thought it would be easy to do based on the prefix of the tuning parameters: For each entry point, only attempt to tune the parameters that have a matching prefix. However, I don't think that'll work if we have functions calling other functions:

```futhark
let bar(...) =
  ...

let main(...) =
  ... bar is not used here ...

entry foo() =
  ... bar is used here ...
```

How will the autotuner know that tuning parameters related to `bar` should only be tuned when running the `foo` entry point?

**Comment by athas** [comment]
The threshold parameters are named for each *entry point*.  In practice, `bar` is always inlined.

**Comment by Munksgaard** [comment]
> The threshold parameters are named for each _entry point_. In practice, `bar` is always inlined.

I see! In that case I'll see what I can do to include that change.

**Comment by Munksgaard** [comment]
Do we have any testing for the autotune feature?

**Comment by athas** [comment]
Nope, not yet!

**Comment by athas** [comment]
Does this approach maintain already existing threshold parameters for entry points that are not being tuned?  It's not a blocker if it doesn't; we can add that later.

**Comment by Munksgaard** [comment]
I don't think it's currently possible to selectively choose which entry points to tune or not. All entry points are tuned each time the autotuner is run, as far as I can tell, so that shouldn't be an issue.

**Pull request merged**
