### PR TITLE
Support hexadecimal float literals in lexer and parser

### PR DESCRIPTION
**Pull request by samrat**
See: https://github.com/diku-dk/futhark/issues/382

This does not include changes for Python and C readers.

### CODE REVIEW

**Comment by Athas** [comment]
How come using hexadecimal literals in the test input works when you didn't implement it in the C reader?  Does it also work with the Python backend (which is not automatically run by Travis for sad reasons)?  Try `futhark-test --compiler=futhark-py`.

**Comment by samrat** [comment]
Erm, turns out the test runner doesn't quite behave the way I thought it did. The test input goes through the Alex lexer(`Futhark.Test.Values` calls `scanTokens`). So, the values the compiled Futhark program sees are the "normal", decimal floats(converted from the hexadecimal literals in `fromHexRealLit`).

The test I added do test the changes to the lexer and parser-- it's just that the values are scanned by `futhark-test` and not the reader. If the inputs were scanned directly by the reader, the test I wrote would have failed. 

I could change my test so that `main` just returns a tuple with two arrays:

```
let main (): ([]f64, []f32) =
    ([0xf.fp2f64], [...])
```

Let me know what you think.

**Comment by Athas** [comment]
Oh yeah, I forgot that `futhark-test` applies its own lexing.  However, I would prefer if the new syntax is actually present in the test program (but having it in the input is also good).

**Comment by samrat** [comment]
Alright, updated the commit with the test.

**Pull request merged**
