### PR TITLE
Add progress bar to autotune commnad

### PR DESCRIPTION
**Pull request by amir**
Addressing #1008

### CODE REVIEW

**Comment by athas** [comment]
Looks like a good start to me.

Regarding `futhark autotune`, I think there are two separate (although nested) things that could do with progress bars: datasets for the current run, and the overall progress through the parameters being tuned.  I think the latter is easier to start with.

**Comment by StarScape** [comment]
What is the status of this? I might be interested in grabbing #1008 if @amir is no longer working on it. Could always branch off the work he's already done here.

**Comment by athas** [comment]
I don't think @amir is working actively on this, so feel free to give it a shot!

**Comment by amir** [comment]
@StarScape please feel free to give it a shot, I'm unable to work on it at the moment.

**Comment by athas** [comment]
Closing seems this seems to be stalled.

**Pull request closed without merging**
