### PR TITLE
Add support for any sized arrays with Map and Reduce prototypes

### PR DESCRIPTION
**Pull request by michael-elkh**
We can now apply the soacs prototypes to any given array.

### CODE REVIEW

**Comment by michael-elkh** [comment]
@athas, I thought I could merge it directly, but it seems that, unfortunately, I don't have the rights.

**Comment by athas** [comment]
I have invited you, but you have not accepted the invitation.  Check your email archives; these links are hard to find in the web UI (and I cannot resend).

**Comment by michael-elkh** [comment]
> I have invited you, but you have not accepted the invitation. Check your email archives; these links are hard to find in the web UI (and I cannot resend).

You're right, I missed it. The link has expired, apparently you have to cancel and resend the invitation. I am really sorry about that.

**Comment by michael-elkh** [comment]
Thank you, sorry again.

**Pull request merged**
