### PR TITLE
Interpret byte-arrays (u8) as greyscale images

### LINKED ISSUE #1278: futhark literate :img should interpret u8 as greyscale
"should" is perhaps a strong word, but `u8` seems to me like a better format to store greyscale information in.

### PR DESCRIPTION
**Pull request by Munksgaard**
Fixes #1278

### CODE REVIEW

**Comment by athas** [comment]
Then how will we represent 8 bit RGB images?

**Comment by Munksgaard** [comment]
> Then how will we represent 8 bit RGB images?

Hm, good question...

**Comment by Munksgaard** [comment]
It might also be nice to be able to interpret [][]bool as a a black and white picture.

**Comment by athas** [comment]
`f32` is in practice often used for greyscale values.  Nobody uses eight-bit colours for data processing, but `u8` is certainly a common storage format.

**Pull request merged**
