### PR TITLE
Header guards

### PR DESCRIPTION
**Pull request by mxxo**
An attempt to add header guards to generated C headers, resolving #718. @athas, may I ask your advice on where to draw the filename from? I thought I could use one of the generated function filepaths but this ended up evaluating to GenericC.hs instead of the C file like I intended. 

Thank you very much for your time. 
Max

### CODE REVIEW

**Comment by athas** [comment]
As a first approximation, I think hard-coded header guard names are fine.  After that (or alternatively), we'll need to extend `GenericC.compileProg` to take as argument a `String` that indicates the source file name.  This is not particularly difficult, but it requires plumbing it all the way through from the [c](https://github.com/diku-dk/futhark/blob/master/src/Futhark/CLI/C.hs) and [opencl](https://github.com/diku-dk/futhark/blob/master/src/Futhark/CLI/OpenCL.hs) subcommands.

Also, be careful with your commits.  This pull request also has some commits related to fixing typos.

**Comment by mxxo** [comment]
Right, thank you very much. I'll separate out the unrelated files from this branch.

**Comment by mxxo** [comment]
Hi there, sorry about the force push! I'll make sure to keep things well separated in the future.

**Comment by kfl** [comment]
You could also just use `#pragma once` as guard. It should be supported by all modern C compilers.

**Comment by athas** [comment]
I'd be OK with `#pragma once`.

Your current patch is inconsistent in that the `#ifdef` is added explicitly to `headerdefs`, while the `#endif` is added with `headerDecl`.  The latter is only for dynamically constructing the contents, so I'd prefer the `#endif` to also be put in `headerdefs` (if you don't decide to go with `#pragma once`).

**Comment by mxxo** [comment]
Thank you both for your help, this seems much cleaner and doesn't change the compileProg interface

**Pull request merged**
