### PR TITLE
Revert "Merge master into multicore."

### PR DESCRIPTION
**Pull request by HnimNart**
Reverts diku-dk/futhark#1083

### CODE REVIEW

**Comment by athas** [comment]
What exactly is going on here?  It doesn't look like current `master` is reflected in `multicore` anymore.

**Comment by HnimNart** [comment]
Oops seems like I messed up. I thought the later PR u sent included these reverted changes.

**Comment by HnimNart** [comment]
What's a good way to undo my mess?

**Comment by athas** [comment]
Revert the revert, I think.

**Pull request merged**
