### PR TITLE
Add support for higher-order functions.

### PR DESCRIPTION
**Pull request by ahovgaard**
See issue #323.

### CODE REVIEW

**Comment by Athas** [comment]
Cool!  I'll take a closer look tomorrow.

**Comment by Athas** [comment]
Travis reports a problem with [issue481.fut](https://github.com/diku-dk/futhark/blob/master/tests/issue481.fut).  Looks like a type substitution is missing somewhere.  A similar error occurs for [lud.fut](https://github.com/diku-dk/futhark-benchmarks/blob/master/rodinia/lud/lud.fut), so I think it's the same issue.

A more interesting failure is with [kmeans.fut](https://github.com/diku-dk/futhark-benchmarks/blob/master/accelerate/kmeans/kmeans.fut), which fails with:

```
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
After internalisation:
In function recentre_2601
A unique tuple element of return value of function recentre_2601 is aliased to some other tuple component.
```

The problem seems to be that the type of the local function `recentre` is incorrectly inferred to be unique (or maybe only the lifted version is?), although it's not yet clear to me where, how, or why.

**Comment by Athas** [comment]
The return type of `recentre` is changed from Nonunique to Unique after the defunctionaliser.  Specifically, the return looks like this after the monomorphiser:

```
Array (ArrayRecordElem
(fromList [(Name "1",RecordArrayElem (ArrayPrimElem (FloatType
Float32) ())),(Name "2",RecordArrayElem (ArrayPrimElem (FloatType
Float32) ()))])) (ShapeDecl {shapeDims = [NamedDim (QualName
{qualQuals = [], qualLeaf = VName (Name "k") 2462})]})
Nonunique
```

And this after defunctionalisation:

```
Array (ArrayRecordElem
(fromList [(Name "1",RecordArrayElem (ArrayPrimElem (FloatType
Float32) ())),(Name "2",RecordArrayElem (ArrayPrimElem (FloatType
Float32) ()))])) (ShapeDecl {shapeDims = [AnyDim]}) Unique
```

**Comment by ahovgaard** [comment]
The k-means benchmark works now. I just needed to combine the shape and uniqueness information from the original return type in a local function with the type of the defunctionalized body, just as for top-level value bindings. By the way, I don't think the return type on `recentre` actually has the named size `k`.

**Comment by Athas** [comment]
Right, it doesn't.  (But that's fine.). I have run my benchmarks, and there is no performance regression.  As soon as you squash your commits, I'll merge this.

**Comment by Athas** [comment]
Futhark is now a higher-order programming language!

**Pull request merged**
