### PR TITLE
futhark-literate: Add :audio directive

### PR DESCRIPTION
**Pull request by Munksgaard**
So far it only handles 8-bit audio at 44100 Hz, but we should be able to extend it if needed.

### CODE REVIEW

**Comment by Munksgaard** [comment]
I will write a literate example for the Futhark website at some point.

**Comment by athas** [comment]
Does the test also verify that the tone is pleasant?

**Comment by Munksgaard** [comment]
I am unsure how best to quantify the pleasentness of a sound. Perhaps we need a test harness with someone strapped into it, who will be exposed to the result of this test everytime something is pushed to the repository.

**Comment by athas** [comment]
Two obvious next steps:

1. Add a codec option so you can get ffmpeg to compress the audio.  Wave is not really usable for Internet distribution.
2. Support chunking, like the video command, so the entire sound does not have to fit in memory at once.  (Maybe not important; I have no idea how much space sound consumes.)

**Comment by Munksgaard** [comment]
Also 32 bit and 16 bit audio (http://trac.ffmpeg.org/wiki/audio%20types) and specifying a different frequency.

**Pull request merged**
