### PR TITLE
Drop hpack.

### PR DESCRIPTION
**Pull request by athas**

### CODE REVIEW

**Comment by flip111** [comment]
what's the motivation to drop hpack support ?

**Comment by athas** [comment]
Mostly Windows.  Also to eliminate an intermediate step when using `cabal`-based builds, which is what e.g. Homebrew prefers.

**Comment by flip111** [comment]
What's the problem of hpack on windows and mac? Maybe hpack can be improved.

**Comment by athas** [comment]
Nothing deep.  On Windows the main problem is that `hpack` isn't in Chocolatey.  On Homebrew the problem isn't so great, because `hpack` is available (after I added it), but I guess it's simpler for users that they don't have to run it.

**Comment by flip111** [comment]
Wouldn't including the generated cabal file into the repository be enough to avoid running hpack? Then hpack can be used by contributors of futhark.

**Comment by athas** [comment]
Sure, but it's yet another moving part that can break, and I can no longer justify the cost.

**Comment by flip111** [comment]
This is an even stronger motivation why to drop hpack support https://gist.github.com/merijn/8152d561fb8b011f9313c48d876ceb07#so-which-tool-should-i-use

**Pull request merged**
