### PR TITLE
Enable the LMAD representation

### PR DESCRIPTION
**Pull request by nqpz**
The code generator now uses index function operations in the LMAD domain.

There are not yet any optimisations on programs in the LMAD domain.

Also add environment variable `IXFUNTRACE` which, if set, shows a trace of which index function operations have resulted in a index function on a line below the actual index function comment line.  This is useful w.r.t. LMADs.

For simplicity we currently only go into the LMAD domain at the end of the passes in the ExplicitMemory representation, with the goal that this is where the LMAD-based optimisations will occur.  If we want to go into the LMAD domain earlier (which might enable us to get completely rid of the algebraic representation), the current LMAD representation will need to be augmented to properly please the type checker, produce correct results for 'isDirect', and stay more inside the single-LMAD domain.

The LMAD module also fixes a few bugs in the previous Lmad module.

All tests and benchmarks that pass with the code in master also pass with the code in this branch, with both the `c` and `opencl` backends (I haven't tested any of the other backends).

Here are the benchmark measurements with the `opencl` backend on one of the GTX 780 Ti's:

```
./Sune-ImageProc/interp.fut
  data/fake.in:                                                         1.00x

./Sune-ImageProc/interp_cos_plays.fut
  data/fake.in:                                                         0.98x

./accelerate/canny/canny.fut
  data/lena256.in:                                                      1.00x
  data/lena512.in:                                                      1.00x

./accelerate/crystal/crystal.fut
  #0 ("200i32 30.0f32 5i32 1i32 1.0f32"):                               1.03x
  #4 ("2000i32 30.0f32 50i32 1i32 1.0f32"):                             1.00x
  #5 ("4000i32 30.0f32 50i32 1i32 1.0f32"):                             1.00x

./accelerate/fft/fft.fut
  data/256x256.in:                                                      0.87x
  data/128x512.in:                                                      1.15x
  data/64x256.in:                                                       1.00x
  data/512x512.in:                                                      1.00x
  data/1024x1024.in:                                                    1.00x
  data/128x128.in:                                                      1.12x

./accelerate/fluid/fluid.fut
  benchmarking/medium.in:                                               1.09x

./accelerate/hashcat/hashcat.fut
  rockyou.dataset:                                                      1.00x

./accelerate/kmeans/kmeans.fut
  data/trivial.in:                                                      0.95x
  data/k5_n50000.in:                                                    1.03x
  data/k5_n200000.in:                                                   1.00x

./accelerate/mandelbrot/mandelbrot.fut
  #0 ("800i32 600i32 -0.7f32 0.0f32 3.067f32 100i32 16.0f..."):         1.00x
  #1 ("1000i32 1000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         1.00x
  #2 ("2000i32 2000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         1.00x
  #3 ("4000i32 4000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         1.00x
  #4 ("8000i32 8000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         1.01x

./accelerate/nbody/nbody.fut
  data/1000-bodies.in:                                                  0.99x
  data/10000-bodies.in:                                                 1.00x
  data/100000-bodies.in:                                                1.01x

./accelerate/pagerank/pagerank.fut
  data/small.in:                                                        1.00x
  data/random_medium.in:                                                1.00x

./accelerate/ray/trace.fut
  #0 ("800i32 600i32 100i32 50.0f32 -100.0f32 -700.0f32 1..."):         1.00x

./accelerate/tunnel/tunnel.fut
  #0 ("10.0f32 800i32 600i32"):                                         1.00x
  #1 ("10.0f32 1000i32 1000i32"):                                       1.00x
  #2 ("10.0f32 2000i32 2000i32"):                                       1.02x
  #3 ("10.0f32 4000i32 4000i32"):                                       1.00x
  #4 ("10.0f32 8000i32 8000i32"):                                       1.00x

./finpar/LocVolCalib.fut
  LocVolCalib-data/small.in:                                            1.00x
  LocVolCalib-data/medium.in:                                           1.00x
  LocVolCalib-data/large.in:                                            1.00x

./finpar/OptionPricing.fut
  OptionPricing-data/small.in:                                          1.01x
  OptionPricing-data/medium.in:                                         1.00x
  OptionPricing-data/large.in:                                          1.00x

./jgf/crypt/crypt.fut
  crypt-data/medium.in:                                                 1.06x

./jgf/crypt/keys.fut
  crypt-data/userkey0.txt:                                              0.97x

./jgf/series/series.fut
  data/10000.in:                                                        0.99x
  data/100000.in:                                                       1.00x
  data/1000000.in:                                                      1.00x

./misc/bfast/bfast-cloudy.fut
  data/sahara-cloudy.in:                                                1.01x

./misc/bfast/bfast.fut
  data/sahara.in:                                                       1.00x

./misc/heston/heston32.fut
  data/1062_quotes.in:                                                  0.97x
  data/10000_quotes.in:                                                 1.02x
  data/100000_quotes.in:                                                1.00x

./misc/heston/heston64.fut
  data/1062_quotes.in:                                                  0.99x
  data/10000_quotes.in:                                                 1.00x
  data/100000_quotes.in:                                                1.00x

./misc/radix_sort/radix_sort_blelloch_benchmark.fut
  data/radix_sort_10K.in:                                               0.90x
  data/radix_sort_100K.in:                                              1.00x
  data/radix_sort_1M.in:                                                1.02x

./misc/radix_sort/radix_sort_large.fut
  data/radix_sort_10K.in:                                               1.00x
  data/radix_sort_100K.in:                                              1.01x
  data/radix_sort_1M.in:                                                1.00x

./parboil/mri-q/mri-q.fut
  data/small.in:                                                        1.00x
  data/large.in:                                                        1.00x

./parboil/sgemm/sgemm.fut
  data/tiny.in:                                                         1.03x
  data/small.in:                                                        0.92x
  data/medium.in:                                                       1.00x

./parboil/stencil/stencil.fut
  data/small.in:                                                        1.00x
  data/default.in:                                                      1.00x

./parboil/tpacf/tpacf.fut
  data/small.in:                                                        1.01x
  data/medium.in:                                                       1.00x
  data/large.in:                                                        1.00x

./rodinia/backprop/backprop.fut
  data/small.in:                                                        1.15x
  data/medium.in:                                                       1.00x

./rodinia/bfs/bfs_asympt_ok_but_slow.fut
  data/4096nodes.in:                                                    1.02x
  data/512nodes_high_edge_variance.in:                                  1.06x
  data/graph1MW_6.in:                                                   1.00x
  data/64kn_32e-var-1-256-skew.in:                                      1.00x

./rodinia/bfs/bfs_filt_padded_fused.fut
  data/4096nodes.in:                                                    0.97x
  data/512nodes_high_edge_variance.in:                                  1.00x
  data/graph1MW_6.in:                                                   1.00x
  data/64kn_32e-var-1-256-skew.in:                                      1.02x

./rodinia/bfs/bfs_heuristic.fut
  data/4096nodes.in:                                                    0.90x
  data/512nodes_high_edge_variance.in:                                  0.91x
  data/graph1MW_6.in:                                                   1.01x
  data/64kn_32e-var-1-256-skew.in:                                      0.99x

./rodinia/bfs/bfs_iter_work_ok.fut
  data/4096nodes.in:                                                    0.96x
  data/512nodes_high_edge_variance.in:                                  0.99x
  data/graph1MW_6.in:                                                   1.00x
  data/64kn_32e-var-1-256-skew.in:                                      0.99x

./rodinia/cfd/cfd.fut
  data/fvcorr.domn.097K.toa:                                            1.00x
  data/fvcorr.domn.193K.toa:                                            1.00x

./rodinia/hotspot/hotspot.fut
  data/64.in:                                                           0.92x
  data/512.in:                                                          1.00x
  data/1024.in:                                                         1.00x

./rodinia/kmeans/kmeans.fut
  data/100.in:                                                          1.00x
  data/204800.in:                                                       1.00x
  data/kdd_cup.in:                                                      0.99x

./rodinia/lavaMD/lavaMD.fut
  data/3_boxes.in:                                                      1.01x
  data/10_boxes.in:                                                     1.00x

./rodinia/lud/lud-clean.fut
  data/16by16.in:                                                       0.83x
  data/64.in:                                                           0.99x
  data/256.in:                                                          1.01x
  data/512.in:                                                          0.99x
  data/2048.in:                                                         1.00x

./rodinia/lud/lud.fut
  data/16by16.in:                                                       1.03x
  data/64.in:                                                           0.96x
  data/256.in:                                                          0.99x
  data/512.in:                                                          1.00x
  data/2048.in:                                                         1.00x

./rodinia/myocyte/myocyte.fut
  data/small.in:                                                        1.00x
  data/medium.in:                                                       1.55x

./rodinia/nn/nn.fut
  data/medium.in:                                                       0.95x

./rodinia/nw/nw.fut
  data/large.in:                                                        1.00x

./rodinia/particlefilter/particlefilter.fut
  data/128_128_10_image_10000_particles.in:                             1.01x
  data/128_128_10_image_400000_particles.in:                            1.00x

./rodinia/pathfinder/pathfinder.fut
  data/medium.in:                                                       1.00x

./rodinia/srad/srad.fut
  data/image.in:                                                        1.01x
```

I'm not sure what is going on with myocyte, but it is consistently faster when LMADs are used for code generation (I have also benchmarked it on my own GPU).  I have looked at the ImpCode programs and dumped OpenCL programs, and there doesn't appear to be any differences other than the order of subexpressions in additions and multiplications, but I must have missed something.

### CODE REVIEW

**Comment by athas** [comment]
Great to see a myocyte speedup!

I don't like the fact that we will be left with *three* distinct index function representations.  I can accept two, and only if one is exclusively used for testing.  I think we should not merge this until the final issues with LMADs are resolved, but I am willing to be convinced otherwise.

**Comment by nqpz** [comment]
Current status: I managed to make `rebase` handle a few more edge cases (without making it too incomprehensible), so the type checker is much more happy now.  All tests and benchmarks still validate.  There is only one test left that doesn't type check when LMAD index functions are used exclusively:

**`streamRed_interchange.fut`** (and the kmeans benchmark, which the test is based on):

The type checker generates this offset:

add32 (add32 (add32 (mul32 (group_id_6804) (mul32 (mul32 (group_size_6786) (nfeatures_6647)) (nclusters_6649))) (local_tid_6803)) (mul32 (i_6782) (mul32 (group_size_6786) (nfeatures_6647)))) (mul32 (group_size_6786) (i_6778))

The compiler passes generate this offset:

add32 (add32 (mul32 (group_id_6804) (mul32 (mul32 (group_size_6786) (nfeatures_6647)) (nclusters_6649))) (local_tid_6803)) (mul32 (group_size_6786) (add32 (mul32 (i_6782) (nfeatures_6647)) (i_6778)))

The expressions describe the same value, but the type checker has expanded part of the expression a bit.

Let k = (add32 (mul32 (group_id_6804) (mul32 (mul32 (group_size_6786) (nfeatures_6647)) (nclusters_6649))) (local_tid_6803)).

Then the type checker generates
```
k + mul32 (i_6782) (mul32 (group_size_6786) (nfeatures_6647))
  + mul32 (group_size_6786) (i_6778)
```
and the compiler passes generate
```
k + mul32 (add32 (mul32 (i_6782) (nfeatures_6647)) (i_6778)) (group_size_6786)
=
k + mul32 (mul32 (i_6782) (nfeatures_6647)) (group_size_6786)
  + mul32 (i_6778) group_size_6786
```

I'm not sure how to go about handling index function unification in this case.  The easiest way might be to modify the compiler passes to generate the index function in more of the same order as the type checker.  But maybe that's just postponing problems we might run into later.

I might also go in later today and make the module use `Data.List.NonEmpty`.

**Comment by athas** [comment]
It would not be too hard to make those index functions equal via some simple algebraic normalisation.  However, I'd rather figure out why they are different to begin with - maybe we can just fix that.

**Comment by coancea** [comment]
|k + mul32 (add32 (mul32 (i_6782) (nfeatures_6647)) (i_6778)) 
(group_size_6786) = k + mul32 (mul32 (i_6782) (nfeatures_6647)) 
(group_size_6786) + mul32 (i_6778) group_size_6786|


This is equivalent to proving:

k + (|i_6782| *|nfeatures_6647 +||i_6778||| ) * |group_size_6786 ==

k + i_6782 * |||nfeatures_6647 * |||||group_size_6786 + ||||i_6778||* 
||group_size_6786

A very simplified version of the algebraic simplifier can handle this 
case easily
because, in essence, the algebraic simplifier normalizes everything to 
sum of products,
hence the two expressions will be normalized to the same expression.

Maybe the solution is to re-plug the strictly-necessary functionality of the
algebraic simplifier (so that it does not become very compile-time 
consuming)

Cosmin


|

**Comment by nqpz** [comment]
Regarding the different offsets:

The type checker generates the index function
```
slice (rebase new_base (iota ns)) is
```
while the compiler passes generate the index function
```
rebase new_base (slice (iota ns) is)
```

In the first case, the final offset is generated directly from the slice `is` (combined with the offset in `new_base`).  In the latter case, the final offset is generated *indirectly* from the slice `is`: The inner index function `(slice (iota ns) is)` already has the offset `add32 (mul32 (i_6782) (nfeatures_6647)) (i_6778)`, which the `rebase` operation tries to handle as best as it can.  However, the information that `(slice (iota ns) is)` is actually a slice has been lost due to the compact nature of the LMAD representation.

I don't think spending time on forcing different compositions of `rebase` and `slice` to produce the exact same expression is worth it, so I suggest we do a little algebraic simplification when comparing values.

**Comment by athas** [comment]
Alternatively, why not recompute the LetAttrs in memory expansion?  That would allow us to get rid of most rebases, potentially even all of them.  (It's a bit unclear whether we can do that with `offsetMemoryInBodyReturns`).

**Comment by nqpz** [comment]
By the way, this works well now (no regressions in pass rate or benchmark efficiency).  Do you want me to squash it?

**Comment by athas** [comment]
Yes.

**Comment by nqpz** [comment]
Should we keep the IXFUNTRACE debug environment variable feature around?

**Comment by athas** [comment]
I'd rather not.

**Pull request merged**
