### PR TITLE
Experiment to see if we can fix failing windows build on azure pipeline

### PR DESCRIPTION
**Pull request by Munksgaard**

### CODE REVIEW

**Comment by athas** [comment]
Futhark requires at least GHC 8.8, so this will not fly.

**Comment by athas** [comment]
Looks like the boulder stayed up this time.  Ready to merge?

**Comment by Munksgaard** [comment]
I think so!

**Comment by flip111** [comment]
Does this mean futhark works on windows again ?

**Comment by athas** [comment]
Yes.

**Pull request merged**
