### PR TITLE
futhark profile fixup

### PR DESCRIPTION
**Pull request by nhey**
Minor fixes related to multiple entry points/programs that I noticed while trying out the new profiling CLI.

### CODE REVIEW

**Comment by athas** [comment]
Fair enough with the typo, but what is the problem with colons in filenames?  Are subdirectories more convenient?  I'm fine if you think it's easier to navigate; I haven't yet used this with a program with many entry points.

**Comment by nhey** [comment]
Removing them was just an easy fix to the fact that `dropExtension "prog.fut:entry"` drops `.fut:entry`. I can change it to preserve colons somehow.

**Comment by athas** [comment]
No, maybe these subdirectories are for the best.

**Comment by nhey** [comment]
On second thought, `dropExtension` shouldn't even make sense after applying `encode`, hm.

**Comment by athas** [comment]
Right, that's bad.  But I do think subdirectories for entry points is better.  I have seen some programs with a dozen entry points, and if you have several data sets for each, then a single directory becomes very unwieldy.  Although you'll have to write some code that splits off the entry point at the end.

**Comment by nhey** [comment]
The above should do it.

**Pull request merged**
