### PR TITLE
Add log1p

### PR DESCRIPTION
**Pull request by nbos**
Works fine in interpreter, but when compiled with backend `c`, `multicore`, even `python`, it underflows to 0.0 for small (absolute) values, as if it were implemented as `log1p x = log (1 + x)`

### CODE REVIEW

**Comment by nbos** [comment]
#1820

**Comment by athas** [comment]
Nice work.  All that is missing is tests, right?

**Comment by nbos** [comment]
The tests pass, but calling it manually it still looks like it underflows:
Compile `entry main (x: f32) : f32 = f32.log1p x` with any CPU backend and pipe `echo 1e-12 | ./test`; it returns `0.000000f32` instead of expected `1e-12f32`.

**Comment by athas** [comment]
Isn't t that just because the text printer uses only six digits? Try -b and inspect the raw bytes.

**Comment by nbos** [comment]
You're right it's the printer, even `id` turns `1e-12` into `0.000000f32`

**Comment by athas** [comment]
Do you have a name for the changelog entry or will you just go by nbos?

**Comment by nbos** [comment]
I'll go by nbos

**Comment by athas** [comment]
Great, thanks for the contribution!

**Comment by athas** [comment]
Thanks for the contribution!

**Pull request merged**
