### PR TITLE
Use 64-bit atomics in OpenCL and CUDA backends.

### PR DESCRIPTION
**Pull request by athas**

### CODE REVIEW

**Comment by athas** [comment]
This will need some testing.  I am pretty sure it works fine on NVIDIA and AMD implementations, but I have no idea about Intel GPUs, since 64-bit atomics are technically an extension.  Any volunteers?

**Comment by Munksgaard** [comment]
> This will need some testing. I am pretty sure it works fine on NVIDIA and AMD implementations, but I have no idea about Intel GPUs, since 64-bit atomics are technically an extension. Any volunteers?

I can try

**Comment by Munksgaard** [comment]
Something is definitely not right on my machine: [test.log](https://github.com/diku-dk/futhark/files/5909424/test.log)

That's the log from running `futhark test -c --backend=opencl --exclude=no_opencl tests/ futhark-benchmarks/` with a3a7d9834bbb49122863b4d6b79beb0df0bf0b6d

**Comment by Munksgaard** [comment]
It all looks something like this:

```
tests/tupleTest.fut:
After sending command ["outputs","main"] to server process:fd:58: hGetLine: end of file
Server process exited unexpectedly with exit code: 255
Server stderr:
Build log:
stringInput.cl:1503:10: error: call to 'atomic_add' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:89:18: note: expanded from macro 'atom_add'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:26:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:27:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:28:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:29:18: note: candidate function
stringInput.cl:1511:10: error: call to 'atomic_add' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:89:18: note: expanded from macro 'atom_add'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:26:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:27:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:28:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:29:18: note: candidate function
stringInput.cl:1525:13: error: call to 'atomic_cmpxchg' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:99:22: note: expanded from macro 'atom_cmpxchg'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:81:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:82:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:83:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:84:18: note: candidate function
stringInput.cl:1541:13: error: call to 'atomic_cmpxchg' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:99:22: note: expanded from macro 'atom_cmpxchg'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:81:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:82:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:83:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:84:18: note: candidate function
stringInput.cl:1551:10: error: call to 'atomic_max' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:96:18: note: expanded from macro 'atom_max'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:59:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:60:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:65:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:66:19: note: candidate function
stringInput.cl:1559:10: error: call to 'atomic_max' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:96:18: note: expanded from macro 'atom_max'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:59:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:60:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:65:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:66:19: note: candidate function
stringInput.cl:1567:10: error: call to 'atomic_min' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:95:18: note: expanded from macro 'atom_min'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:56:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:57:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:62:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:63:19: note: candidate function
stringInput.cl:1575:10: error: call to 'atomic_min' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:95:18: note: expanded from macro 'atom_min'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:56:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:57:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:62:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:63:19: note: candidate function
stringInput.cl:1583:10: error: call to 'atomic_max' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:96:18: note: expanded from macro 'atom_max'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:59:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:60:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:65:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:66:19: note: candidate function
stringInput.cl:1591:10: error: call to 'atomic_max' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:96:18: note: expanded from macro 'atom_max'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:59:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:60:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:65:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:66:19: note: candidate function
stringInput.cl:1599:10: error: call to 'atomic_min' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:95:18: note: expanded from macro 'atom_min'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:56:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:57:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:62:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:63:19: note: candidate function
stringInput.cl:1607:10: error: call to 'atomic_min' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:95:18: note: expanded from macro 'atom_min'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:56:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:57:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:62:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:63:19: note: candidate function
stringInput.cl:1615:10: error: call to 'atomic_and' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:91:18: note: expanded from macro 'atom_and'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:36:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:37:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:38:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:39:18: note: candidate function
stringInput.cl:1623:10: error: call to 'atomic_and' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:91:18: note: expanded from macro 'atom_and'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:36:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:37:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:38:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:39:18: note: candidate function
stringInput.cl:1631:10: error: call to 'atomic_or' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:92:17: note: expanded from macro 'atom_or'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:41:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:42:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:43:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:44:18: note: candidate function
stringInput.cl:1639:10: error: call to 'atomic_or' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:92:17: note: expanded from macro 'atom_or'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:41:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:42:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:43:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:44:18: note: candidate function
stringInput.cl:1647:10: error: call to 'atomic_xor' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:93:18: note: expanded from macro 'atom_xor'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:46:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:47:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:48:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:49:18: note: candidate function
stringInput.cl:1655:10: error: call to 'atomic_xor' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:93:18: note: expanded from macro 'atom_xor'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:46:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:47:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:48:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:49:18: note: candidate function
stringInput.cl:1663:10: error: call to 'atomic_xor' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:93:18: note: expanded from macro 'atom_xor'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:46:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:47:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:48:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:49:18: note: candidate function
stringInput.cl:1671:10: error: call to 'atomic_xor' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:93:18: note: expanded from macro 'atom_xor'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:46:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:47:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:48:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:49:18: note: candidate function
stringInput.cl:1680:10: error: call to 'atomic_cmpxchg' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:99:22: note: expanded from macro 'atom_cmpxchg'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:81:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:82:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:83:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:84:18: note: candidate function
stringInput.cl:1689:10: error: call to 'atomic_cmpxchg' is ambiguous
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:99:22: note: expanded from macro 'atom_cmpxchg'
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:81:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:82:19: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:83:18: note: candidate function
/nix/store/36yfbq1wyxzfcifr15r9mbklc5c7nbsg-beignet-unstable-2018.08.20/lib/beignet/include/ocl_atom.h:84:18: note: candidate function

./tests/tupleTest: tests/tupleTest.c:4396: OpenCL call
  build_opencl_program(prog, device_option.device, compile_opts)
failed with error code -2 (Device not available)
```

**Comment by athas** [comment]
That might mean Beignet just doesn't support 64-bit atomics, but it's weird that it doesn't complain about the extension enabling them.  Could you try their new driver?  I think it's called "Iris".  Beignet is not maintained anymore, so if that's the only one that breaks, I'm willing to just let it break.

**Comment by athas** [comment]
Oh, and does it work with `master` in the first place?  Those `atomic_`-functions are the 32-bit variants...

**Comment by Munksgaard** [comment]
Not everything works for me on master. Here's the log: 
[master.log](https://github.com/diku-dk/futhark/files/5913048/master.log). Not as many failures as on this branch.

I'll try with something other than beignet.

**Comment by Munksgaard** [comment]
Using the [Intel Compute Runtime](https://search.nixos.org/packages?channel=unstable&show=intel-compute-runtime&from=0&size=50&sort=relevance&query=intel-compute-runtime) seemed to fix all my problems, including successfully running tests that did not previously pass. :+1:

**Comment by Munksgaard** [comment]
When running `futhark test` on the futhark-benchmarks directory, I still get 
[a handful of errors](https://github.com/diku-dk/futhark/files/5913398/test.log), but I don't think that has anything to do with this PR.

**Pull request merged**
