### PR TITLE
Change size parameters and annotations to be of type `i64`

### LINKED ISSUE #134: Convert Futhark to 64-bit
The Futhark compiler is presently tied heavily to the 32-bit world.  Not only are all dimension sizes and loop indices 32-bit (signed!) integers, but the generated code also has these assumptions.  Clearly this is not going to fly in the long run.  I don't want to mix 32-bit and 64-bit sizes, so we should just move everything to 64-bit, always.  Should the `int` type also default to 64-bit?  I think that might be a little confusing.

I did a few experiments, and 64-bit integer arithmetic does not seem to be noticeably slower on the GPU, and we rarely have arrays of sizes, so programs should not end up using more storage.

### PR DESCRIPTION
**Pull request by athas**
This is the big one that finally resolves #134.  The strategy here has been to both internally and externally require all sizes to be of type `i64`.  In the core language, all indexes is also of this type, while the source language permits some polymorphism there (can be any signed integer type).

The changes to the compiler itself are fairly straightforward - basically just search/replace.  But this is such an enormous compatibility-breaking change that there is much left to decide and to do:

- [x] What should be the type of functions such as `r32`?  Presently they are e.g. `r32 : i32 -> f32`, but perhaps that is less useful when `i32` becomes a less privileged type. **Resolution: keep them as they are.**
- [x] Similarly, should we change the type of integer literals with no type suffix in test data?  Presently these are interpreted as `i32`?  Extending type inference to test data is *not* possible. **Resolution: keep them i32.**
- [x] Fix the programs in our test suite.  This is tedious and boring, but mostly not very difficult.  As of this writing, almost 200 still fail. **Done.**
- [x] [Fix all packages](https://futhark-lang.org/pkgs/).  This probably requires creating a branch (which I tend to call `futhark64`) which can be maintained until the 64-bit change makes it into a release of the Futhark compiler.  This part will *really* suck, because `futhark pkg` does not provide any way to download package dependencies from a nonstandard branch.  Fortunately, most packages are pretty small. **The packages used in the benchmarks have been fixed.  The others will follow after this is merged.**
- [x] Fix the benchmark suite.  I've already started on this, and it is mostly not annoying, but it sometimes requires a little thought to decide where the types should actually change.  The futhark-benchmarks repository directly embeds all its package dependencies, so we can just directly fix them there.  It's ugly, but tolerable in the short term.

My timeline for finishing all this is early November or late October.  I want to have this done before the DIKU course on PFP starts, because I don't want to change the type system while students are working with Futhark, and I don't want to delay until PFP is over.

This will be painful, but I *think* it is the last time we have to fundamentally change anything in Futhark.  At least I can't think of any other design defects (we have lots of other *limitations*, but those can be fixed without breaking compatibility).  Let's just get this over with.

### CODE REVIEW

**Comment by Munksgaard** [comment]
Holy moly! Let me know if there's anything you want help with. I can take a look at some of the packages and tests perhaps?

**Comment by athas** [comment]
The packages are a PITA to deal with, because it's basically about manually copying files around, so I think it is easier if I just do that (starting with the packages that are needed to run the benchmarks).  But feel free to take a swing at the tests; those are pretty straightforward.

**Comment by athas** [comment]
64-bit compared to 32-bit for Parboil:

```
parboil/histo/histo.fut
  data/default.in:                                                      1.00x
  data/large.in:                                                        0.99x

parboil/mri-q/mri-q.fut
  data/large.in:                                                        1.01x
  data/small.in:                                                        0.99x

parboil/sgemm/sgemm.fut
  data/tiny.in:                                                         0.99x
  data/small.in:                                                        1.06x
  data/medium.in:                                                       0.97x

parboil/stencil/stencil.fut
  data/default.in:                                                      0.98x
  data/small.in:                                                        1.00x

parboil/tpacf/tpacf.fut
  data/large.in:                                                        1.00x
  data/small.in:                                                        0.98x
  data/medium.in:                                                       1.00x
```

No problems there.  Here's Rodinia:

```
rodinia/backprop/backprop.fut
  data/small.in:                                                        1.01x
  data/medium.in:                                                       1.00x

rodinia/bfs/bfs_asympt_ok_but_slow.fut
  data/64kn_32e-var-1-256-skew.in:                                      1.00x
  data/512nodes_high_edge_variance.in:                                  0.99x
  data/graph1MW_6.in:                                                   0.86x
  data/4096nodes.in:                                                    0.98x

rodinia/bfs/bfs_filt_padded_fused.fut
  data/64kn_32e-var-1-256-skew.in:                                      0.92x
  data/512nodes_high_edge_variance.in:                                  0.96x
  data/graph1MW_6.in:                                                   0.78x
  data/4096nodes.in:                                                    1.00x

rodinia/bfs/bfs_heuristic.fut
  data/64kn_32e-var-1-256-skew.in:                                      0.98x
  data/512nodes_high_edge_variance.in:                                  0.99x
  data/graph1MW_6.in:                                                   0.75x
  data/4096nodes.in:                                                    0.97x

rodinia/bfs/bfs_iter_work_ok.fut
  data/64kn_32e-var-1-256-skew.in:                                      0.93x
  data/512nodes_high_edge_variance.in:                                  0.97x
  data/graph1MW_6.in:                                                   0.77x
  data/4096nodes.in:                                                    0.95x

rodinia/cfd/cfd.fut
  data/fvcorr.domn.193K.toa:                                            1.00x
  data/fvcorr.domn.097K.toa:                                            1.00x

rodinia/hotspot/hotspot.fut
  data/512.in:                                                          1.05x
  data/1024.in:                                                         1.07x
  data/64.in:                                                           1.04x

rodinia/kmeans/kmeans.fut
  data/kdd_cup.in:                                                      0.99x
  data/100.in:                                                          1.01x
  data/204800.in:                                                       0.99x

rodinia/lavaMD/lavaMD.fut
  data/3_boxes.in:                                                      1.00x
  data/10_boxes.in:                                                     0.99x

rodinia/lud/lud.fut
  data/512.in:                                                          0.91x
  data/64.in:                                                           0.92x
  data/256.in:                                                          0.91x
  data/16by16.in:                                                       0.96x
  data/2048.in:                                                         1.01x

rodinia/myocyte/myocyte.fut
  data/small.in:                                                        0.98x
  data/medium.in:                                                       0.91x

rodinia/nn/nn.fut
  data/medium.in:                                                       0.99x

rodinia/nw/nw.fut
  data/large.in:                                                        1.00x

rodinia/particlefilter/particlefilter.fut
  data/128_128_10_image_400000_particles.in:                            1.00x
  data/128_128_10_image_10000_particles.in:                             0.98x

rodinia/pathfinder/pathfinder.fut
  data/medium.in:                                                       0.93x

rodinia/srad/srad.fut
  data/image.in:                                                        0.99x
```

Spot the odd one if you can.

**Comment by athas** [comment]
I have fixed the entire benchmark suite.  Here is the impact of using 64-bit sizes on an RTX 2080 Ti with the CUDA backend, excluding the microbenchmarks:

```
futhark-benchmarks/accelerate/canny/canny.fut
  data/lena512.in:                                                      0.90x
  data/lena256.in:                                                      1.04x

futhark-benchmarks/accelerate/crystal/crystal.fut
  #0 ("200i32 30.0f32 5i32 1i32 1.0f32"):                               1.01x
  #4 ("2000i32 30.0f32 50i32 1i32 1.0f32"):                             0.98x
  #5 ("4000i32 30.0f32 50i32 1i32 1.0f32"):                             0.99x

futhark-benchmarks/accelerate/fft/fft.fut
  data/64x256.in:                                                       0.99x
  data/128x512.in:                                                      1.00x
  data/1024x1024.in:                                                    0.97x
  data/512x512.in:                                                      0.97x
  data/256x256.in:                                                      0.96x
  data/128x128.in:                                                      0.95x

futhark-benchmarks/accelerate/fluid/fluid.fut
  benchmarking/medium.in:                                               0.93x

futhark-benchmarks/accelerate/hashcat/hashcat.fut
  rockyou.dataset:                                                      0.81x

futhark-benchmarks/accelerate/kmeans/kmeans.fut
  data/k5_n50000.in:                                                    0.93x
  data/trivial.in:                                                      0.94x
  data/k5_n200000.in:                                                   0.85x

futhark-benchmarks/accelerate/mandelbrot/mandelbrot.fut
  #1 ("1000i32 1000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         0.99x
  #3 ("4000i32 4000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         1.00x
  #2 ("2000i32 2000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         0.98x
  #0 ("800i32 600i32 -0.7f32 0.0f32 3.067f32 100i32 16.0f..."):         1.00x
  #4 ("8000i32 8000i32 -0.7f32 0.0f32 3.067f32 100i32 16...."):         0.98x

futhark-benchmarks/accelerate/nbody/nbody-bh.fut
  data/10000-bodies.in:                                                 1.00x
  data/100000-bodies.in:                                                0.97x
  data/1000-bodies.in:                                                  0.95x

futhark-benchmarks/accelerate/nbody/nbody.fut
  data/10000-bodies.in:                                                 0.98x
  data/100000-bodies.in:                                                1.00x
  data/1000-bodies.in:                                                  1.03x

futhark-benchmarks/accelerate/pagerank/pagerank.fut
  data/small.in:                                                        0.98x
  data/random_medium.in:                                                0.97x

futhark-benchmarks/accelerate/ray/trace.fut
  #0 ("800i32 600i32 100i32 50.0f32 -100.0f32 -700.0f32 1..."):         0.98x

futhark-benchmarks/accelerate/smoothlife/smoothlife.fut
  #1 ("256i32"):                                                        1.01x
  #2 ("512i32"):                                                        0.98x
  #3 ("1024i32"):                                                       0.96x
  #0 ("128i32"):                                                        0.97x

futhark-benchmarks/accelerate/tunnel/tunnel.fut
  #1 ("10.0f32 1000i32 1000i32"):                                       1.01x
  #4 ("10.0f32 8000i32 8000i32"):                                       0.93x
  #0 ("10.0f32 800i32 600i32"):                                         1.01x
  #2 ("10.0f32 2000i32 2000i32"):                                       0.99x
  #3 ("10.0f32 4000i32 4000i32"):                                       1.01x

futhark-benchmarks/finpar/LocVolCalib.fut
  LocVolCalib-data/small.in:                                            0.97x
  LocVolCalib-data/medium.in:                                           0.91x
  LocVolCalib-data/large.in:                                            0.91x

futhark-benchmarks/finpar/OptionPricing.fut
  OptionPricing-data/medium.in:                                         0.97x
  OptionPricing-data/small.in:                                          0.91x
  OptionPricing-data/large.in:                                          1.00x

futhark-benchmarks/jgf/crypt/crypt.fut
  crypt-data/medium.in:                                                 0.89x

futhark-benchmarks/jgf/crypt/keys.fut
  crypt-data/userkey0.txt:                                              0.98x

futhark-benchmarks/jgf/series/series.fut
  data/1000000.in:                                                      1.00x
  data/10000.in:                                                        1.02x
  data/100000.in:                                                       1.00x

futhark-benchmarks/misc/bfast/bfast-cloudy.fut
  data/peru.in:                                                         1.01x
  data/sahara-cloudy.in:                                                1.04x

futhark-benchmarks/misc/bfast/bfast.fut
  data/sahara.in:                                                       0.96x

futhark-benchmarks/misc/heston/heston32.fut
  data/1062_quotes.in:                                                  0.91x
  data/10000_quotes.in:                                                 1.00x
  data/100000_quotes.in:                                                1.01x

futhark-benchmarks/misc/heston/heston64.fut
  data/1062_quotes.in:                                                  0.99x
  data/10000_quotes.in:                                                 1.00x
  data/100000_quotes.in:                                                1.00x

futhark-benchmarks/misc/knn-by-kdtree/buildKDtree.fut
  valid-data/kdtree-ppl-32-m-2097152.in:                                0.33x

futhark-benchmarks/misc/knn-by-kdtree/driver-knn.fut
  256i32 [2097152][7]f32 [10000000][7]f32:                              0.92x

futhark-benchmarks/misc/poseidon/poseidon-bench.fut:arity11
  [17600000]u64:                                                        0.99x

futhark-benchmarks/misc/poseidon/poseidon-bench.fut:arity8
  [22400000]u64:                                                        0.99x

futhark-benchmarks/misc/radix_sort/radix_sort_blelloch_benchmark.fut
  data/radix_sort_100K.in:                                              0.96x
  data/radix_sort_10K.in:                                               1.10x
  data/radix_sort_1M.in:                                                0.96x

futhark-benchmarks/misc/radix_sort/radix_sort_large.fut
  data/radix_sort_100K.in:                                              0.93x
  data/radix_sort_10K.in:                                               0.96x
  data/radix_sort_1M.in:                                                0.99x

futhark-benchmarks/parboil/histo/histo.fut
  data/default.in:                                                      0.98x
  data/large.in:                                                        0.99x

futhark-benchmarks/parboil/mri-q/mri-q.fut
  data/large.in:                                                        1.01x
  data/small.in:                                                        1.00x

futhark-benchmarks/parboil/sgemm/sgemm.fut
  data/tiny.in:                                                         0.91x
  data/small.in:                                                        0.96x
  data/medium.in:                                                       0.98x

futhark-benchmarks/parboil/stencil/stencil.fut
  data/default.in:                                                      0.98x
  data/small.in:                                                        1.00x

futhark-benchmarks/parboil/tpacf/tpacf.fut
  data/large.in:                                                        0.99x
  data/small.in:                                                        1.00x
  data/medium.in:                                                       1.01x

futhark-benchmarks/pbbs/ray/ray.fut
  data/angel.in:                                                        1.00x
  data/dragon.in:                                                       0.99x
  data/happy.in:                                                        1.00x

futhark-benchmarks/rodinia/backprop/backprop.fut
  data/small.in:                                                        0.95x
  data/medium.in:                                                       1.00x

futhark-benchmarks/rodinia/bfs/bfs_asympt_ok_but_slow.fut
  data/64kn_32e-var-1-256-skew.in:                                      0.97x
  data/512nodes_high_edge_variance.in:                                  0.91x
  data/graph1MW_6.in:                                                   0.83x
  data/4096nodes.in:                                                    0.99x

futhark-benchmarks/rodinia/bfs/bfs_filt_padded_fused.fut
  data/64kn_32e-var-1-256-skew.in:                                      0.91x
  data/512nodes_high_edge_variance.in:                                  0.99x
  data/graph1MW_6.in:                                                   0.78x
  data/4096nodes.in:                                                    0.94x

futhark-benchmarks/rodinia/bfs/bfs_heuristic.fut
  data/64kn_32e-var-1-256-skew.in:                                      1.03x
  data/512nodes_high_edge_variance.in:                                  0.95x
  data/graph1MW_6.in:                                                   0.75x
  data/4096nodes.in:                                                    0.86x

futhark-benchmarks/rodinia/bfs/bfs_iter_work_ok.fut
  data/64kn_32e-var-1-256-skew.in:                                      0.93x
  data/512nodes_high_edge_variance.in:                                  0.95x
  data/graph1MW_6.in:                                                   0.81x
  data/4096nodes.in:                                                    0.93x

futhark-benchmarks/rodinia/cfd/cfd.fut
  data/fvcorr.domn.193K.toa:                                            0.99x
  data/fvcorr.domn.097K.toa:                                            0.99x

futhark-benchmarks/rodinia/hotspot/hotspot.fut
  data/512.in:                                                          1.03x
  data/1024.in:                                                         1.06x
  data/64.in:                                                           1.01x

futhark-benchmarks/rodinia/kmeans/kmeans.fut
  data/kdd_cup.in:                                                      0.96x
  data/100.in:                                                          1.02x
  data/204800.in:                                                       0.94x

futhark-benchmarks/rodinia/lavaMD/lavaMD.fut
  data/3_boxes.in:                                                      1.00x
  data/10_boxes.in:                                                     0.96x

futhark-benchmarks/rodinia/lud/lud.fut
  data/512.in:                                                          0.93x
  data/64.in:                                                           0.90x
  data/256.in:                                                          0.94x
  data/16by16.in:                                                       1.02x
  data/2048.in:                                                         1.02x

futhark-benchmarks/rodinia/myocyte/myocyte.fut
  data/small.in:                                                        0.93x
  data/medium.in:                                                       0.87x

futhark-benchmarks/rodinia/nn/nn.fut
  data/medium.in:                                                       0.95x

futhark-benchmarks/rodinia/nw/nw.fut
  data/large.in:                                                        0.98x

futhark-benchmarks/rodinia/particlefilter/particlefilter.fut
  data/128_128_10_image_400000_particles.in:                            1.05x
  data/128_128_10_image_10000_particles.in:                             0.98x

futhark-benchmarks/rodinia/pathfinder/pathfinder.fut
  data/medium.in:                                                       0.71x

futhark-benchmarks/rodinia/srad/srad.fut
  data/image.in:                                                        1.00x
```

**Comment by Munksgaard** [comment]
That doesn't look too bad, does it?

**Comment by athas** [comment]
This is tolerable, and there may even be ways to improve the remainder.  I have not looked closely at them.

**Comment by athas** [comment]
We still need to come to a decision about `r32`/`t32` and the types of unadorned literals in test data.

**Comment by athas** [comment]
This is no longer a draft.  All tests and benchmarks work locally,  There is still a little final investigation to do, to minimise the performance impact (and measure it accurately).  I would also like to do a final 32-bit release before merging this.

**Comment by athas** [comment]
The major buildKDTree.fut slowdown is because the bottleneck is apparently a bunch of radix-sorting by key, which is now more expensive as the keys (indexes) are 64-bit integers.  I am not going to fix this.  Cosmin can deal with it by writing a dedicated 32-bit sort when he notices.

**Comment by athas** [comment]
The coming week I will release a new version.  Immediately after that, I will merge this PR.  We can then spend a little time speeding things up and updating packages, but it is my intent to relatively quickly make a release with these changes.  I would like @HnimNart's new backend to be part of that release, though.

**Comment by athas** [comment]
Interestingly, using 64-bit sizes makes the multicore backend *faster* on many benchmarks, e.g. OptionPricing.  Slower on others.  Nothing terribly dramatic.

**Comment by athas** [comment]
I am tired of staring at this one, so let's just merge and we'll clean up the mess as it appears.

**Pull request merged**
