### PR TITLE
Cuda code-generation of chained-scan with decoupled lookback

### PR DESCRIPTION
**Pull request by mortentc**
As per my Master's Thesis "Regular Segmented Single-pass Scan in Futhark", this PR implements code generation of a single-pass segmented scan in CUDA in [SegSinglePass.hs](https://github.com/mortentc/futhark/blob/master/src/Futhark/CodeGen/ImpGen/Kernels/SegScan/SegSinglePass.hs).
The current code-generator still defaults to Persson & Nicolaisen's implementation when the [collection to be scanned is not segmented](https://github.com/mortentc/futhark/blob/e695d835a7835cf487b6ffa9e88cbc34c7c89fc3/src/Futhark/CodeGen/ImpGen/Kernels/SegScan.hs#L65-L68), which avoids unnecessarry index calculations, but does not make use of the [analytical memory model for sequential work](https://github.com/mortentc/futhark/blob/e695d835a7835cf487b6ffa9e88cbc34c7c89fc3/src/Futhark/CodeGen/ImpGen/Kernels/SegScan/SegSinglePass.hs#L115-L132).

### CODE REVIEW

**Comment by athas** [comment]
How difficult do you think it would be to incorporate the analytical model in the non-segmented scan?

**Comment by athas** [comment]
This is solid work thanks!  I think the conflict is something fairly trivial (I'll take a look).

**Comment by athas** [comment]
Oh, the conflict is only for rebasing; no worry then.

**Comment by athas** [comment]
Could you please fix the style errors, though?  [All Futhark code is formatted with Ormolu.](https://github.com/diku-dk/futhark/blob/master/STYLE.md#ormolu)

**Comment by mortentc** [comment]
> How difficult do you think it would be to incorporate the analytical model in the non-segmented scan?

There should be no difficulties, in the non-segmented scan the degree is [hardcoded](https://github.com/mortentc/futhark/blob/e695d835a7835cf487b6ffa9e88cbc34c7c89fc3/src/Futhark/CodeGen/ImpGen/Kernels/SegScan/SinglePass.hs#L117), so replacing the line 'm=9' with the [analytical model](https://github.com/mortentc/futhark/blob/e695d835a7835cf487b6ffa9e88cbc34c7c89fc3/src/Futhark/CodeGen/ImpGen/Kernels/SegScan/SegSinglePass.hs#L115-L132) should be enough.

> Could you please fix the style errors, though? All Futhark code is formatted with Ormolu.
I will take a look at the style, apologies.

**Comment by athas** [comment]
Thanks, excellent work!

**Pull request merged**
