### PR TITLE
Don't output tty control codes if the terminal is dumb

### LINKED ISSUE #1000: Executing `futhark test` in a dumb terminal produces a lot of unnecessary output
For instance, running `futhark test` through an eshell inside emacs will output something like this:

```
┌──────────┬────────┬────────┬───────────┐
│          │ passed │ failed │ remaining │
├──────────┼────────┼────────┼───────────┤
│ programs │ 1392   │ 0      │ 3/1395    │
├──────────┼────────┼────────┼───────────┤
│ runs     │ 2353   │ 0      │ 139/2492  │
└──────────┴────────┴────────┴───────────┘
...
┌──────────┬────────┬────────┬───────────┐
│          │ passed │ failed │ remaining │
├──────────┼────────┼────────┼───────────┤
│ programs │ 1393   │ 0      │ 2/1395    │
├──────────┼────────┼────────┼───────────┤
│ runs     │ 2392   │ 0      │ 100/2492  │
└──────────┴────────┴────────┴───────────┘
...
┌──────────┬────────┬────────┬───────────┐
│          │ passed │ failed │ remaining │
├──────────┼────────┼────────┼───────────┤
│ programs │ 1394   │ 0      │ 1/1395    │
├──────────┼────────┼────────┼───────────┤
│ runs     │ 2428   │ 0      │ 64/2492   │
└──────────┴────────┴────────┴───────────┘
...
┌──────────┬────────┬────────┬───────────┐
│          │ passed │ failed │ remaining │
├──────────┼────────┼────────┼───────────┤
│ programs │ 1395   │ 0      │ 0/1395    │
├──────────┼────────┼────────┼───────────┤
│ runs     │ 2492   │ 0      │ 0/2492    │
└──────────┴────────┴────────┴───────────┘
...
```

Which goes on and on for as many times as there are tests. Perhaps we should detect if the output terminal is dumb (edit: meaning `TERM=dumb`), in which case we should handle the output like with `--notty`.

### PR DESCRIPTION
**Pull request by Munksgaard**
Fixes #1000

### CODE REVIEW

**Comment by athas** [comment]
Is `TERM=dumb` set by anything else than Emacs?

**Comment by Munksgaard** [comment]
I'm pretty sure `dumb` is a valid predefined TERM variable, it's even mentioned in the TERM(7) manual: https://linux.die.net/man/7/term. It may be used in other contexts, though I haven't run in to any.

That said, if your question is "is this really worth supporting, if the only plausible use case is someone using eshell to run futhark test?", I don't know. If your question is "is there perhaps a better way to do this?", I'm sure there is. A more general solution would be to explicitly check the term capabilities to see if moving the cursor is actually supported.

**Comment by athas** [comment]
This is worth supporting, it just doesn't address the issue of CI services claiming to be terminals, yet not supporting common control codes.

**Comment by Munksgaard** [comment]
> This is worth supporting, it just doesn't address the issue of CI services claiming to be terminals, yet not supporting common control codes.

Does that happen? Where?

**Comment by Munksgaard** [comment]
Ah, you're talking about having to explicitly pass `--no-terminal` in the CI?

**Comment by Munksgaard** [comment]
It actually looks like Github Actions uses the "dumb" terminal as well: 
https://github.com/diku-dk/futhark/pull/1001/checks?check_run_id=737857033#step:6:8

**Comment by Munksgaard** [comment]
Looks like it works without `--no-terminal` now: https://github.com/diku-dk/futhark/pull/1001/checks?check_run_id=737877331#step:8:10

**Pull request merged**
